### ISSUE TITLE
How to remove all objects and push new array

### ISSUE THREAD

**Issue by chrisverra** [hackbrightacademy/Pyrebase_Example#1]
Hi,

Great so far!

However, i want to completely replace my firebase db with my new list.

How to approach?

**Comment by ardinusawan** [comment]
I need to know this to. Is your problem was solved?

**Comment by chrisverra** [comment]
for me it worked like this:
`db.child("someNameHere").child().set(newlist, user['idToken'])`

this completely overwrites whatever is a child of someNameHere. So the entire object of someNameHere is replaced with my list: "newlist:
